name: Codacy coverage

on:
  workflow_run:
    workflows: ["Pest"]
    branches:
      - main
    types:
      - completed

jobs:
  coverage:
    env:
      DB_CONNECTION: sqlite
      SESSION_DRIVER: array
      DB_DATABASE: ":memory:"
      APP_KEY: base64:1NxfrNErQ0vo1ZnPcLeVhnE7tOZdKlKiFORzPA92krM=
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download clover.xml artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY }}
          coverage-reports: clover.xml
