name: Pest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "feature/**"
jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: moox-press
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      SESSION_DRIVER: array
      DB_CONNECTION: mysql
      DB_DATABASE: moox-press
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      APP_KEY: base64:1NxfrNErQ0vo1ZnPcLeVhnE7tOZdKlKiFORzPA92krM=
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [11.*]
        stability: [prefer-latest]
        include:
          - laravel: 11.*
            testbench: 9.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get MySQL IP
        id: get_mysql_ip
        run: |
          MYSQL_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q --filter ancestor=mysql:latest))
          echo "::set-output name=mysql_ip::$MYSQL_IP"

      - name: Dump SQL
        run: |
          MYSQL_IP=${{ steps.get_mysql_ip.outputs.mysql_ip }}
          mysql -u root -h $MYSQL_IP -p$DB_PASSWORD $DB_DATABASE < moox-press.sql

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer update

      - name: List Installed Dependencies
        run: composer show -D

      - name: Prepare .env file
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Execute tests
        run: vendor/bin/pest --coverage-clover clover.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY }}
          coverage-reports: clover.xml
