name: Pest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "feature/**"

jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: moox-press
          MYSQL_USER: root
          MYSQL_PASSWORD: user_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Remove PHP-PSR Extension
        run: |
          sudo apt remove php8.2-psr

      - name: Install dependencies
        run: |
          composer update

      - name: List Installed Dependencies
        run: composer show -D

      - name: Prepare .env file
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Execute tests
        run: vendor/bin/pest --coverage-clover clover.xml
