name: Pest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "feature/**"
jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: moox-press
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      SESSION_DRIVER: array
      DB_CONNECTION: mysql
      DB_DATABASE: moox-press
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      APP_KEY: base64:1NxfrNErQ0vo1ZnPcLeVhnE7tOZdKlKiFORzPA92krM=
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2]
        laravel: [10.*, 11.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 11.*
            testbench: 9.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add other steps here...
      - name: Prepare .env file
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=testdb" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env
      # Continue with your existing steps...
